# config/services.yaml

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Ensure all classes in Diagnostics/Provider are autowired and tagged
    App\Diagnostics\Provider\:
        resource: '../src/Diagnostics/Provider/'
        tags: ['diagnostics.provider'] # Ensures all providers in this directory are tagged

    # Explicitly define arguments for SymfonyDiagnosticsProvider
    # based on its constructor: __construct(string $projectDir)
    App\Diagnostics\Provider\SymfonyDiagnosticsProvider:
        arguments:
            $projectDir: '%kernel.project_dir%'
        tags: ['diagnostics.provider']

    # Define the actual, non-decorated SystemDiagnosticsCollector with a unique internal ID.
    App\Service\SystemDiagnosticsCollector.inner:
        class: App\Service\SystemDiagnosticsCollector
        arguments:
            $providers: !tagged_iterator diagnostics.provider
        public: false

    # Cached version of the diagnostics collector
    App\Service\CachedDiagnosticsCollector:
        arguments:
            $collector: '@App\Service\SystemDiagnosticsCollector.inner'
            $cache: '@cache.app'
            $cacheTtl: 300

    # Alias for the cached collector, used by controllers
    App\Service\SystemDiagnosticsCollectorInterface:
        alias: App\Service\CachedDiagnosticsCollector
        public: true

    # Explicitly configure ApiTokenAuthenticator's constructor argument
    App\Security\ApiTokenAuthenticator:
        arguments:
            $apiToken: '%env(APP_API_TOKEN)%'
