name: CI

on: [push, pull_request]

jobs:
    tests:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.3'
                  extensions: opcache
                  tools: composer
                  # Removed 'cache: true' as it's an unexpected input for this action version/configuration.

            - name: Install dependencies
              run: composer install --no-interaction --prefer-dist

            # FIX: Add a step to ensure php-cs-fixer is available by installing it into vendor/bin
            - name: Install PHP-CS-Fixer
              run: composer require --dev friendsofphp/php-cs-fixer --with-all-dependencies --no-autoloader

            - name: Run PHPUnit tests
              run: vendor/bin/phpunit

            - name: Run PHPStan static analysis
              run: vendor/bin/phpstan analyse src/

            - name: Check code style
              run: vendor/bin/php-cs-fixer fix --dry-run --stop-on-violation
