name: CI

on: [push, pull_request]

jobs:
    tests:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.2'
                  extensions: opcache
                  tools: composer
                  cache: true

            - name: Install dependencies
              run: composer update --prefer-dist --no-interaction

            - name: Run PHPUnit tests
              run: vendor/bin/phpunit

            - name: Run PHPStan static analysis
              run: vendor/bin/phpstan analyse src/

            - name: Check code style
              run: vendor/bin/php-cs-fixer fix --dry-run --stop-on-violation
