name: CI

on: [push, pull_request]

jobs:
    tests:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.3' # FIX: Changed PHP version to 8.3 for better compatibility with PHPUnit 12.x
                  extensions: opcache
                  tools: composer
                  # FIX: Removed 'cache: true' as it's an unexpected input for this action version/configuration.
                  #      Composer cache is often managed automatically or via 'composer-cache: true' if available.

            - name: Install dependencies
              run: composer update --prefer-dist --no-interaction

            - name: Run PHPUnit tests
              run: vendor/bin/phpunit

            - name: Run PHPStan static analysis
              run: vendor/bin/phpstan analyse src/

            - name: Check code style
              run: vendor/bin/php-cs-fixer fix --dry-run --stop-on-violation
